package com.credable.lms.integration.cbs.kyc;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.2
 * 2025-03-21T18:55:29.019+03:00
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "http://credable.io/cbs/customer", name = "CustomerPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerPort {

    @WebMethod(operationName = "Customer")
    @WebResult(name = "CustomerResponse", targetNamespace = "http://credable.io/cbs/customer", partName = "CustomerResponse")
    public CustomerResponse customer(

        @WebParam(partName = "CustomerRequest", name = "CustomerRequest", targetNamespace = "http://credable.io/cbs/customer")
        CustomerRequest customerRequest
    );
}
